import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { supabase } from '../../lib/supabase/client';
import { useAuthStore } from '../../store/useAuthStore';
import { WebNavbar } from '../../components/layout/WebNavbar';
import { WebFooter } from '../../components/layout/WebFooter';

type Address = { id: string; full_name: string; phone: string; street: string; city: string; province: string; postal_code?: string; is_default: boolean };
export default function AddressesScreen() {
  const router = useRouter(); const queryClient = useQueryClient(); const { user } = useAuthStore(); const [form, setForm] = useState({ full_name:'', phone:'', street:'', city:'', province:'', postal_code:'' }); const [saving, setSaving] = useState(false);
  const { data: addresses = [] } = useQuery({ queryKey:['shipping-addresses',user?.id], enabled:!!user?.id, queryFn:async()=>{ const {data,error}=await supabase.from('shipping_addresses').select('*').eq('user_id',user!.id).order('is_default',{ascending:false}); if(error) throw error; return data as Address[]; } });
  const save = async () => { if (!user) { router.push('/(auth)/login'); return; } if (Object.values(form).slice(0,5).some(v => !v.trim())) { Alert.alert('Complete your address', 'Name, phone, street, city and province are required.'); return; } setSaving(true); if (!addresses.length) await supabase.from('shipping_addresses').update({is_default:false}).eq('user_id',user.id); const { error } = await supabase.from('shipping_addresses').insert({...form,user_id:user.id,is_default:addresses.length===0}); setSaving(false); if(error){Alert.alert('Could not save address',error.message);return;} setForm({full_name:'',phone:'',street:'',city:'',province:'',postal_code:''});queryClient.invalidateQueries({queryKey:['shipping-addresses',user.id]}); };
  const makeDefault = async (id:string) => { if(!user)return; await supabase.from('shipping_addresses').update({is_default:false}).eq('user_id',user.id); const {error}=await supabase.from('shipping_addresses').update({is_default:true}).eq('id',id);if(error)Alert.alert('Could not update address',error.message);queryClient.invalidateQueries({queryKey:['shipping-addresses',user.id]});};
  return <View style={styles.page}><WebNavbar/><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Delivery addresses</Text><Text style={styles.intro}>Choose where your protected orders should be delivered.</Text>{addresses.map(a=><View key={a.id} style={styles.card}><View style={styles.cardTop}><View><Text style={styles.name}>{a.full_name}{a.is_default?' · Default':''}</Text><Text style={styles.copy}>{a.street}, {a.city}, {a.province}</Text><Text style={styles.copy}>{a.phone}{a.postal_code?` · ${a.postal_code}`:''}</Text></View>{!a.is_default&&<Pressable onPress={()=>makeDefault(a.id)}><Text style={styles.defaultLink}>Make default</Text></Pressable>}</View></View>)}<View style={styles.form}><Text style={styles.formTitle}>Add a new address</Text><Field label="Full name" value={form.full_name} onChangeText={v=>setForm({...form,full_name:v})}/><Field label="Phone number" value={form.phone} onChangeText={v=>setForm({...form,phone:v})} keyboardType="phone-pad"/><Field label="Street address" value={form.street} onChangeText={v=>setForm({...form,street:v})}/><View style={styles.row}><View style={styles.half}><Field label="City" value={form.city} onChangeText={v=>setForm({...form,city:v})}/></View><View style={styles.half}><Field label="Province" value={form.province} onChangeText={v=>setForm({...form,province:v})}/></View></View><Field label="Postal code (optional)" value={form.postal_code} onChangeText={v=>setForm({...form,postal_code:v})}/><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>{saving?'Saving…':'Save address'}</Text></Pressable></View></ScrollView><WebFooter/></View>;
}
function Field({label,...props}:any){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} placeholder={label} placeholderTextColor="#849292" {...props}/></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#F6F8F8'},content:{maxWidth:760,width:'100%',alignSelf:'center',padding:24,paddingBottom:48},title:{fontSize:28,fontWeight:'800',color:'#263333'},intro:{color:'#718080',marginTop:6,marginBottom:22},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DFE9E8',borderRadius:9,padding:17,marginBottom:10},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:12},name:{fontWeight:'800',color:'#263333',marginBottom:5},copy:{color:'#5D7474',fontSize:13,lineHeight:19},defaultLink:{color:'#007782',fontWeight:'800',fontSize:13},form:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DFE9E8',borderRadius:9,padding:20,marginTop:12},formTitle:{fontSize:18,fontWeight:'800',color:'#263333',marginBottom:8},field:{marginTop:12},label:{fontSize:13,fontWeight:'700',color:'#405757',marginBottom:6},input:{borderWidth:1,borderColor:'#C8D8D7',borderRadius:7,paddingHorizontal:12,paddingVertical:11,color:'#263333'},row:{flexDirection:'row',gap:12},half:{flex:1},save:{backgroundColor:'#007782',borderRadius:7,paddingVertical:14,alignItems:'center',marginTop:19},saveText:{color:'#fff',fontWeight:'800'}});
